version: "3.8"
services: 
    reverse:
        image: nginx
        container_name: reverse
        depends_on: 
            - nodewebapp
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse_proxy/conf.d:/etc/nginx/conf.d/

    nodewebapp:
        image: matredmo/node-webapp
        build: 
            context: ./nodewebapp
        container_name: nodewebapp
        command: node server.js
        ports:
            - 8080:80
        


        